apiVersion: v1
kind: ConfigMap
metadata:
  namespace: rmi-tracing
  name: rmi-tracing-config
data:
  RMI_SERVER_URL: "rmi://rmi-server:1099/UserService"
  CLIENT_SERVER_PORT: "8080"
  CLIENT_APP_NAME: "service-a"
  SERVER_SERVER_PORT: "8081"
  SERVER_APP_NAME: "service-b"
